FROM codejump/meteor:1.0.2

ADD $app$ /home/user/app/

#RUN cd /home/user/app && ls -l

#RUN cd /home/user/app/ # && sudo meteor update 
#&& meteor remove insecure
#RUN cd /home/user/app && sudo meteor add mquandalle:jade && sudo meteor add ian:accounts-ui-bootstrap-3
#RUN cd /home/user/app && sudo meteor add twbs:bootstrap && sudo meteor add accounts-password
#RUN cd /home/user/app && sudo meteor add iron:router && sudo meteor add dburles:collection-helpers

# Optionally specify versions
#RUN cd /home/user/app && sudo meteor add accounts-ui@=1.1.4
#CMD cd /home/user/app/Meteor && sudo meteor --port 8081